### ISSUE TITLE
Краш приложения при подключении плагина Konfeature

### ISSUE THREAD

**Issue by EmogurovAnton** [RedMadRobot/debug-panel-android#33]
При подключении `konfeature` по шагам из `readme` приложение сваливается с ошибкой

`Caused by: com.redmadrobot.konfeature.exception.NoFeatureConfigException: No feature config added`

**Comment by AleksandrTabolin** [comment]
Библиотека требует подключения хотя бы одной конфигурации с тоглами через `register(config)`
